name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  geolocator: ^8.0.5
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  intro_screen_onboarding_flutter: ^0.1.5
  shared_preferences: ^2.0.11
  lottie: ^1.4.1
  google_nav_bar: ^5.0.6
  google_fonts: ^3.0.1
  firebase_core: ^1.20.1
  get: ^4.6.5
  google_sign_in: ^5.4.1
  firebase_auth: ^3.6.3
  connectivity_plus: ^2.3.6+1
  overlay_support: ^2.0.1
  internet_connection_checker: ^0.0.1+4
  flutter_signin_button: ^2.0.0
  introduction_screen: ^3.0.2
  settings_ui: ^2.0.2
  permission_handler: ^10.0.0
  cached_network_image: ^3.2.1
  extended_image: ^6.2.1
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.3
  babstrap_settings_screen: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - Lottie/
