name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  geolocator: ^8.0.5
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.2.0
  intro_screen_onboarding_flutter: ^0.1.5

  flutter_conditional_rendering: ^2.0.0
  shared_preferences: ^2.0.11
  salomon_bottom_bar: ^3.2.0
  lottie: ^1.2.2
  google_nav_bar: ^5.0.5
  avatar_glow: ^2.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900